// Generated by CoffeeScript 1.8.0
var start;

start = function() {
  var app, div, xsize, ysize;
  div = document.getElementById('app');
  xsize = 640;
  ysize = 480;
  app = new App(div, xsize, ysize);
  app.addEffect('fire', function(ctx) {
    return new Fire(ctx, xsize, ysize);
  });
  app.addEffect('starfield', function(ctx) {
    return new Starfield(ctx, xsize, ysize);
  });
  app.addEffect('cube', function(ctx) {
    return new Cube(ctx, xsize, ysize);
  });
  return app.start();
};
// Generated by CoffeeScript 1.8.0
var App,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

App = (function() {
  function App(div, xsize, ysize) {
    var canvas;
    this.div = div;
    this.xsize = xsize;
    this.ysize = ysize;
    this.changeFx = __bind(this.changeFx, this);
    canvas = document.createElement('canvas');
    canvas.width = this.xsize;
    canvas.height = this.ysize;
    this.ctx = canvas.getContext('2d');
    this.div.appendChild(canvas);
    this.fx = null;
    this.ctors = {};
  }

  App.prototype.addEffect = function(name, ctor) {
    var link;
    link = document.createElement('a');
    link.className = 'fxsel';
    link.href = '#' + name;
    link.textContent = name;
    this.ctors[name] = ctor;
    return this.div.appendChild(link);
  };

  App.prototype.start = function() {
    window.onhashchange = this.changeFx;
    return this.changeFx();
  };

  App.prototype.changeFx = function() {
    var ctor, hash;
    if (this.fx != null) {
      this.fx.stop();
    }
    hash = window.location.hash.substring(1 || 'fire');
    ctor = this.ctors[hash];
    return this.fx = ctor(this.ctx);
  };

  return App;

})();
// Generated by CoffeeScript 1.8.0
var FpsCounter;

FpsCounter = (function() {
  function FpsCounter(updateMillis) {
    this.updateMillis = updateMillis;
    this.lastCalledTime = Date.now();
    this.fps = 0;
    this.fpsText = '';
    this.drawFpsReady = false;
  }

  FpsCounter.prototype.start = function() {
    return this.interval = window.setInterval(((function(_this) {
      return function() {
        return _this.drawFpsReady = true;
      };
    })(this)), this.updateMillis);
  };

  FpsCounter.prototype.stop = function() {
    window.clearInterval(this.interval);
    return this.interval = void 0;
  };

  FpsCounter.prototype.tick = function() {
    var delta, now;
    now = Date.now();
    delta = (now - this.lastCalledTime) / 1000;
    this.lastCalledTime = now;
    this.fps = (1 / delta).toFixed(1);
    if (this.drawFpsReady) {
      this.fpsText = this.fps;
      this.drawFpsReady = false;
    }
    return this.fpsText;
  };

  return FpsCounter;

})();
// Generated by CoffeeScript 1.8.0
var Fire,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Fire = (function() {
  function Fire(ctx, xsize, ysize) {
    var buf;
    this.ctx = ctx;
    this.xsize = xsize;
    this.ysize = ysize;
    this.drawFrame = __bind(this.drawFrame, this);
    this.buffer1 = this.makeBuffer();
    this.buffer2 = this.makeBuffer();
    this.cooling = this.makeBuffer();
    this.imageData = ctx.getImageData(0, 0, this.xsize, this.ysize);
    buf = new ArrayBuffer(this.imageData.data.length);
    this.buf8 = new Uint8ClampedArray(buf);
    this.data = new Uint32Array(buf);
    this.coolingOffset = 0;
    this.prepareCoolingBuffer();
    this.fpsCounter = new FpsCounter(1000);
    this.fpsCounter.start();
    this.request = window.requestAnimationFrame(this.drawFrame);
  }

  Fire.prototype.stop = function() {
    this.fpsCounter.stop();
    window.cancelAnimationFrame(this.request);
    return this.request = void 0;
  };

  Fire.prototype.makeBuffer = function() {
    var buf, x, y, _i, _ref, _results;
    buf = new Array(this.xsize);
    _results = [];
    for (x = _i = 0, _ref = this.xsize - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; x = 0 <= _ref ? ++_i : --_i) {
      buf[x] = new Array(this.ysize);
      _results.push((function() {
        var _j, _ref1, _results1;
        _results1 = [];
        for (y = _j = 0, _ref1 = this.ysize - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
          _results1.push(buf[x][y] = 0);
        }
        return _results1;
      }).call(this));
    }
    return _results;
  };

  Fire.prototype.prepareCoolingBuffer = function() {
    var i, randomIntFromInterval, smooth, v, x, y, _i, _j, _results;
    randomIntFromInterval = function(min, max) {
      return Math.floor(Math.random() * (max - min + 1) + min);
    };
    for (i = _i = 1; _i <= 1000; i = ++_i) {
      x = randomIntFromInterval(1, this.xsize - 2);
      y = randomIntFromInterval(1, this.ysize - 2);
      v = randomIntFromInterval(0, 0xff);
      this.cooling[x][y] = v;
    }
    smooth = (function(_this) {
      return function(buf) {
        var dx, dy, newBuf, _j, _k, _l, _m, _ref, _ref1;
        newBuf = _this.makeBuffer();
        for (x = _j = 1, _ref = _this.xsize - 2; 1 <= _ref ? _j <= _ref : _j >= _ref; x = 1 <= _ref ? ++_j : --_j) {
          for (y = _k = 1, _ref1 = _this.ysize - 2; 1 <= _ref1 ? _k <= _ref1 : _k >= _ref1; y = 1 <= _ref1 ? ++_k : --_k) {
            v = 0;
            for (dx = _l = -1; _l <= 1; dx = ++_l) {
              for (dy = _m = -1; _m <= 1; dy = ++_m) {
                v += buf[x + dx][y + dy];
              }
            }
            v /= 9;
            newBuf[x][y] = v;
          }
        }
        return newBuf;
      };
    })(this);
    _results = [];
    for (i = _j = 1; _j <= 50; i = ++_j) {
      _results.push(this.cooling = smooth(this.cooling));
    }
    return _results;
  };

  Fire.prototype.drawFrame = function() {
    var avalue, bvalue, c, fpsText, gvalue, index, n1, n2, n3, n4, p, rvalue, v, value, x, y, ydest, _i, _j, _k, _l, _ref, _ref1, _ref2, _ref3, _ref4;
    this.request = window.requestAnimationFrame(this.drawFrame);
    for (y = _i = _ref = this.ysize - 3, _ref1 = this.ysize - 1; _ref <= _ref1 ? _i <= _ref1 : _i >= _ref1; y = _ref <= _ref1 ? ++_i : --_i) {
      for (x = _j = 0, _ref2 = this.xsize - 1; 0 <= _ref2 ? _j <= _ref2 : _j >= _ref2; x = 0 <= _ref2 ? ++_j : --_j) {
        this.buffer1[x][y] = 0x80;
      }
    }
    for (y = _k = 1, _ref3 = this.ysize - 2; 1 <= _ref3 ? _k <= _ref3 : _k >= _ref3; y = 1 <= _ref3 ? ++_k : --_k) {
      for (x = _l = 1, _ref4 = this.xsize - 2; 1 <= _ref4 ? _l <= _ref4 : _l >= _ref4; x = 1 <= _ref4 ? ++_l : --_l) {
        n1 = this.buffer1[x + 1][y];
        n2 = this.buffer1[x - 1][y];
        n3 = this.buffer1[x][y + 1];
        n4 = this.buffer1[x][y - 1];
        c = this.cooling[x][(y + this.coolingOffset) % this.ysize];
        p = (n1 + n2 + n3 + n4) / 4;
        p = p - c;
        if (p < 0) {
          p = 0;
        }
        ydest = y - 1;
        this.buffer2[x][ydest] = p;
        index = ydest * this.xsize + x;
        value = p;
        rvalue = value;
        gvalue = value;
        bvalue = value;
        avalue = 0xff;
        v = rvalue;
        v |= gvalue << 8;
        v |= bvalue << 16;
        v |= avalue << 24;
        this.data[index] = v;
      }
    }
    this.imageData.data.set(this.buf8);
    this.ctx.putImageData(this.imageData, 0, 0);
    this.buffer1 = this.buffer2;
    this.coolingOffset++;
    fpsText = this.fpsCounter.tick();
    this.ctx.fillStyle = "red";
    return this.ctx.fillText(fpsText, 10, 10);
  };

  return Fire;

})();
// Generated by CoffeeScript 1.8.0
var Starfield,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Starfield = (function() {
  function Starfield(ctx, xsize, ysize) {
    var nstars, _;
    this.ctx = ctx;
    this.xsize = xsize;
    this.ysize = ysize;
    this.drawFrame = __bind(this.drawFrame, this);
    nstars = 200;
    this.stars = (function() {
      var _i, _results;
      _results = [];
      for (_ = _i = 1; 1 <= nstars ? _i <= nstars : _i >= nstars; _ = 1 <= nstars ? ++_i : --_i) {
        _results.push(this.randomStar());
      }
      return _results;
    }).call(this);
    this.request = window.requestAnimationFrame(this.drawFrame);
  }

  Starfield.prototype.randomStar = function() {
    var x, y;
    x = Math.floor(Math.random() * this.xsize);
    y = Math.floor(Math.random() * this.ysize);
    return [x, y];
  };

  Starfield.prototype.stop = function() {
    window.cancelAnimationFrame(this.request);
    return this.request = void 0;
  };

  Starfield.prototype.drawFrame = function() {
    var x, y, _i, _len, _ref, _ref1;
    this.request = window.requestAnimationFrame(this.drawFrame);
    this.ctx.fillStyle = "black";
    this.ctx.fillRect(0, 0, this.xsize, this.ysize);
    this.ctx.fillStyle = "white";
    _ref = this.stars;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      _ref1 = _ref[_i], x = _ref1[0], y = _ref1[1];
      this.ctx.fillRect(x, y, 1, 1);
    }
    return this.scatterStars();
  };

  Starfield.prototype.scatterStars = function() {
    var accel, dx, dy, i, newStar, x, y, _i, _len, _ref, _ref1, _results;
    _ref = this.stars;
    _results = [];
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      _ref1 = _ref[i], x = _ref1[0], y = _ref1[1];
      accel = 0.01;
      dx = accel * (x - (this.xsize / 2));
      dy = accel * (y - (this.ysize / 2));
      newStar = [x + dx, y + dy];
      if (!this.inbounds(newStar)) {
        newStar = this.randomStar();
      }
      _results.push(this.stars[i] = newStar);
    }
    return _results;
  };

  Starfield.prototype.inbounds = function(_arg) {
    var x, y;
    x = _arg[0], y = _arg[1];
    return (0 <= x) && (x < this.xsize) && (0 <= y) && (y < this.xsize);
  };

  return Starfield;

})();
// Generated by CoffeeScript 1.8.0
var Cube,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Cube = (function() {
  function Cube(ctx, xsize, ysize) {
    var a, b, c, d, e, f, g, h;
    this.ctx = ctx;
    this.xsize = xsize;
    this.ysize = ysize;
    this.drawFrame = __bind(this.drawFrame, this);
    this.request = window.requestAnimationFrame(this.drawFrame);
    a = [-1, -1, -1];
    b = [+1, -1, -1];
    c = [-1, +1, -1];
    d = [+1, +1, -1];
    e = [-1, -1, +1];
    f = [+1, -1, +1];
    g = [-1, +1, +1];
    h = [+1, +1, +1];
    this.edges = [[a, b], [a, c], [b, d], [c, d], [e, f], [e, g], [f, h], [g, h], [a, e], [b, f], [c, g], [d, h]];
    this.frameNum = 0;
  }

  Cube.prototype.stop = function() {
    window.cancelAnimationFrame(this.request);
    return this.request = void 0;
  };

  Cube.prototype.drawFrame = function() {
    var omega, p1, p2, position, x1, x2, y1, y2, _i, _len, _ref, _ref1, _ref2, _ref3;
    this.request = window.requestAnimationFrame(this.drawFrame);
    omega = 0.05;
    this.frameNum++;
    position = {
      x: 3 * Math.cos(omega * this.frameNum),
      y: 3 * Math.sin(omega * this.frameNum),
      z: -10
    };
    this.ctx.fillStyle = "black";
    this.ctx.fillRect(0, 0, this.xsize, this.ysize);
    this.ctx.strokeStyle = "white";
    this.ctx.beginPath();
    _ref = this.edges;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      _ref1 = _ref[_i], p1 = _ref1[0], p2 = _ref1[1];
      _ref2 = this.threeToTwo(p1, position), x1 = _ref2[0], y1 = _ref2[1];
      _ref3 = this.threeToTwo(p2, position), x2 = _ref3[0], y2 = _ref3[1];
      this.ctx.moveTo(x1, y1);
      this.ctx.lineTo(x2, y2);
    }
    return this.ctx.stroke();
  };

  Cube.prototype.threeToTwo = function(_arg, position) {
    var px, py, pz, sx, sy, x, y, z, zoom;
    px = _arg[0], py = _arg[1], pz = _arg[2];
    x = position.x - px;
    y = position.y - py;
    z = position.z - pz;
    zoom = Math.min(this.xsize, this.ysize);
    sx = zoom * (x / z - position.x / position.z) + this.xsize / 2;
    sy = zoom * (y / z - position.y / position.z) + this.ysize / 2;
    return [sx, sy];
  };

  return Cube;

})();
